#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/rogerfar/rdtclient
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: 2.0.29

# -- environment variables. See more environment variables in the [calibre-web documentation](https://github.com/linuxserver/docker-calibre-web#parameters).
# @default -- See below
env: null

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 6500

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /data/db
    size: 500Mi
    accessMode: ReadWriteOnce
    storageClass: longhorn
  downloads:
    enabled: true
    mountPath: /data/downloads
    size: 50Gi
    accessMode: ReadWriteOnce
    storageClass: longhorn

