# https://taskfile.dev

version: '3'

vars:
  REPO_URL: https://jimkala.github.io/helm-charts
  CHARTS: >-
    rdt-client
    bind9
    readarr
    sabnzbd

includes:
  helm: .taskfiles/helm.yaml
  install: .taskfiles/InstallTasks.yaml

tasks:
  standard:
    cmds:
      - task: helm:lint
      - task: helm:package
      - task: helm:index
    silent: true
  publish:
    cmds:
      - task: standard
    silent: true
