#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: eafxx/bind
  # -- image pull policy
  pullPolicy: IfNotPresent
  # -- image tag
  tag: latest-ccf145d3

# -- environment variables. See more environment variables in the [docker-bind documentation](https://github.com/elmerfdz/docker-bind).
# @default -- See below
env: null

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 10000
  dns:
    enabled: true
    type: LoadBalancer
    ports:
      udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
      tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53

      

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false